# Numpy 패키지

- pandas에서 데이터를 저장 및 처리에 사용되는 패키지

- 외부 패키지로 반드시 설치 필요

- 고속 데이터 처리, 수치 계산 수행 패키지

- 머신러닝/딥러닝용 패키지 Scikit-lern, Tensorflow, PyTorch, Keras 등등에서도
- 내부 데이터 저장 및 수치 계산에 사용되는 패키지

-[중요] 동일한 데이터 타입의 데이터를 저장하는 배열Array 타입

- !pip install numpy

In [15]:
# 버전 확인
import numpy as np

np.__version__

'1.23.0'

## 배열Array
- 순차적으로 데이터를 저장하는 자료형
- 서로 연관있는 데이터를 하나의 변수명으로 저장
- 같은 타입의 변수들로 이루어진 유한 집합으로 정의
- 원소 개수 변경 불가
- 구성하는 각각의 값을 배열 요소/원소element
- 위치를 가리키는 숫자는 인덱스index


- 벡터Vector => 1차원 배열 int array[12]

- 행렬Matrix => 2차원 배열 int array[4][3]

- 다차원배열 => 3차원 이상 배열 int array[1][3][4]


- 배열 - 넘파이 기본 단위 => 고정된 공간에 동일한 데이터 타입 저장
- 리스트 - 파이썬 => 동적 공간에 서로 다른 데이터 타입 저장

- class ndarray(n-dimentional array)
- 행과 열 내의 모든 원소는 동일한 형태의 데이터(all of theelements must be the same type)

In [16]:
# ndarray 객체 생성하기 ==> numpy.array()
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [17]:
type(arr1)

numpy.ndarray

In [18]:
# ndarray 객체 속성 확인하기
# 객체변수명.속성명
arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size
# ndim : 차원 (1,2,3,...)
# shape : 형태 (갯수,), (행,열), (면,행,열)
# dtype : 데이터 타입
# itemsize : 배열 요소의 바이트 크기
# size : 배열 요소 갯수

(1, (3,), dtype('int32'), 4, 3)

In [21]:
# 배열의 요소 즉 아이템, 원소 접근하기
# 0-base 인덱스 자동 지정 => 객체변수명[인덱스]
print(f'객체변수명 : arr1 => {arr1}')
print(f'객체변수명 : arr1[0] => {arr1[0]}')
print(f'객체변수명 : arr1[1] => {arr1[1]}')

객체변수명 : arr1 => [1 2 3]
객체변수명 : arr1[0] => 1
객체변수명 : arr1[1] => 2


In [27]:
# 모든 값을 1으로 채워서 ndarray 객체 생성하는 함수 => ones()
# 근데 정수 아님. 디폴트값 float
arr2=np.array([1,1,1,1])
arr2=np.ones(4, dtype=np.int64)
arr2
# 0 채우고 싶으면 np.zeros()
# 0,1 말고 원하는 값 채우고 싶으면 np.full(배열형태, 값)

array([1, 1, 1, 1], dtype=int64)

In [28]:
arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size

(1, (4,), dtype('int64'), 8, 4)

In [31]:
# 초기화하지 않고 ndarray 객체 생성 할 때는 => mumpy.empty()
arr3=np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# 2차원 형태의 ndarray 객체 생성
arr4=np.array([ [1,2,3,],[4,5,6] ])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr4.shape, arr4.ndim

((2, 3), 2)

In [40]:
# 2차원 => 1차원
arr5=arr4.flatten()
arr5

array([1, 2, 3, 4, 5, 6])

In [41]:
arr5.shape, arr5.ndim

((6,), 1)

In [46]:
# 1차원 => 다른 차원으로 변경 reshape()
arr6=arr5.reshape((1,3,2))     # ((2,3)) 2행, 3열
arr6

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [47]:
arr7=arr6.flatten()
arr7

array([1, 2, 3, 4, 5, 6])

In [50]:
# 차원/형태 변환 => reshape(-1,n), reshape(n,-1)
arr8=np.arange(8)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
arr9=arr8.reshape(-1,2)    # 모르는 자리에 -1 넣으면 2행 기준으로 계산해줌.
arr9

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [55]:
arr9=arr8.reshape(-1,3)    # 비어지는 칸 생기면 오류
arr9

ValueError: cannot reshape array of size 8 into shape (3)

In [56]:
arr9=arr8.reshape(4,-1)
arr9

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])